### ISSUE TITLE
Julia's Task List 

### ISSUE THREAD

**Issue by neoblitz** [jgonik/PassGAN-TF2#1]
**Week 1**

- [x] Get setup with email and access.
- [x] Create your own notes on Overleaf
- [x] Read the PassGAN paper
- [x] Tensorflow tutorials as necessary
- [x] Setup and run the PassGAN code on Colab (refer to Joie's work) 
- [x] Setup and run the PassGAN code on your laptop.
- [x] Setup and run the PassGAN on your deeplearning machine.
- [x] Understand the internals of the PassGAN code.
- [x] Browse: https://github.com/nashory/gans-awesome-applications
- [x] Credit card: https://www.toptal.com/machine-learning/generative-adversarial-networks
- [x] https://nbviewer.jupyter.org/github/codyznash/GANs_for_Credit_Card_Data/blob/master/GAN_comparisons.ipynb
- [x] Meet with Joie and Yuening and discuss next steps.

PassGAN code: https://github.com/d4ichi/PassGAN

**Week 2**
- [ ] Add Joie and Arun to repo. Make repo private
- [ ] Try PassGAN with different filter sizes
- [ ] Try RNN WGAN on IP addresses
- [ ] Look at this https://arxiv.org/pdf/1705.10929.pdf. Contact authors for source code
